spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sep?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC+7
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+7
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 855934457571-e7silhcuj7ml5e4l1fom6hu3k8pb2njk.apps.googleusercontent.com
            clientSecret: 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
            scope: email, profile

  mail:
    host: smtp.gmail.com
    port: 587
    username: tuanld.sil22@gmail.com
    password: awcyioktuuzuuujj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB

server:
  port: 8080

firebase:
  bucket-name: sep490-g28.appspot.com
  image-url: "https://storage.googleapis.com/sep490-g28.appspot.com/%s"

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 3600000
  refresh-secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347438
  refresh-expiration: 7200000
  issuer: vn.com.fpt.gople
